version: '3'

volumes:
  pg_data_fg:
  static:
  media:
  docs:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_fg:/var/lib/postgresql/data
  backend:
    image: alexanderchistyakov/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
      - docs:/app/docs/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: alexanderchistyakov/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: alexanderchistyakov/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/etc/nginx/html/media/
      - docs:/usr/share/nginx/html/api/docs/