# Регистрация пользователя 
GET  http://127.0.0.1:8000/api/users/me/
Content-type: application/json
Authorization: Token 8884e3c9caf1d1b73945d26f58e5243f710dacdd
 
{ 
    "username": "newguy4", 
    "first_name": "new", 
    "last_name": "guy", 
    "email": "test4@tes.ru", 
    "password": "dddddddd8"  
} 
 
### 
# Получение токена 
POST http://127.0.0.1:8000/api/auth/token/login/
Content-type: application/json 
 
{ 
    "email": "test3@tes.ru", 
    "password": "dddddddd8"  
} 
 
### 
#Теги
GET http://127.0.0.1:8000/api/tags/
Content-type: application/json 
Authorization: Token 59d26c097f8e1797363310b0981bce4f6e8f4872 
 
{ 
    "name": "pfsdfdnhfr", 
    "color": "#efefef", 
    "slug": "udsfhsdfin" 
} 
 
### 
#Список ингредиентов 
GET http://127.0.0.1:8000/api/ingredients/ 
Content-type: application/json 
Authorization: Token 59d26c097f8e1797363310b0981bce4f6e8f4872  
 
 
### 
# Создать рецепт 
PATCH http://127.0.0.1:8000/api/recipes/4/
Content-type: application/json 
Authorization: Token 59d26c097f8e1797363310b0981bce4f6e8f4872 
 
{ 
    "ingredients": [ 
        { 
            "id": 1, 
            "amount": 10 
        } 
    ], 
    "tags": [ 
        4, 
        5 
    ], 
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==", 
    "name": "пивасик", 
    "text": "string", 
    "cooking_time": 1 
} 
 
 
### 
# Список рецептов 
POST http://127.0.0.1:8000/api/recipes/4/shopping_cart/
Content-type: application/json 
Authorization: Token 59d26c097f8e1797363310b0981bce4f6e8f4872 
 
 
### 
# Добавление в корзину 
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/ 
Content-type: application/json 
Authorization: Token 5354aab1863b435eb8088373539bbddeba9ee30c