# Generated by Django 3.2.20 on 2023-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231001_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(max_length=10, verbose_name='Название меры'),
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
