# Generated by Django 3.2.20 on 2023-10-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20231011_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Мера(таблица m2m рецепт-ингредиент)', 'verbose_name_plural': 'Мера(таблица m2m рецепт-ингредиент)'},
        ),
    ]
