# Generated by Django 3.2.20 on 2023-10-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='api/default_recipe.jpg', help_text='Загрузка картинки к рецепту', upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
